# Generated by Django 4.2.14 on 2026-02-12 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artificialinsemination',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_farmer': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_assign', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='artificialinsemination',
            name='assigned_to_cooperative',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_cooperative': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_cooperative', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='artificialinsemination',
            name='assigned_to_official',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_official': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_official', to=settings.AUTH_USER_MODEL),
        ),
    ]
