# Generated by Django 3.1.3 on 2022-01-30 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0002_auto_20211231_1154'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Referal_Form',
            new_name='Referral_Form',
        ),
    ]
