# Generated by Django 4.2.11 on 2024-06-18 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlymilkrecord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='weeklymilkrecord',
            name='user',
        ),
    ]
