# Generated by Django 4.2.11 on 2024-07-05 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklymilkrecord',
            old_name='total_quantity',
            new_name='quantity',
        ),
    ]
