# Generated by Django 4.2.14 on 2026-02-12 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0002_alter_artificialinsemination_assigned_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='date_of_leave_request',
        ),
    ]
