# Generated by Django 4.2.14 on 2026-02-12 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0003_remove_leaverequest_date_of_leave_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='date_of_leave_request',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
