# Generated by Django 4.2.14 on 2026-02-12 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0004_leaverequest_date_of_leave_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movementpermits',
            name='date_of_record',
        ),
    ]
