# Generated by Django 4.2.11 on 2024-06-18 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0004_monthlymilkrecord_user_weeklymilkrecord_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlymilkrecord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='weeklymilkrecord',
            name='user',
        ),
    ]
