# Generated by Django 3.1.3 on 2023-02-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0004_auto_20220405_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sick_approach_form',
            name='farmer_username',
            field=models.CharField(choices=[(1, 'Ganja Farmer'), (2, 'ganja Juana'), (3, 'Jeremiah George')], max_length=12, verbose_name='Farmer Username'),
        ),
    ]
