# Generated by Django 4.2.11 on 2024-07-06 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0004_rename_quantity_dailymilkrecord_total_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregnancymonitoring',
            name='action_to_take',
        ),
        migrations.RemoveField(
            model_name='pregnancymonitoring',
            name='approximate_preg_months',
        ),
        migrations.RemoveField(
            model_name='pregnancymonitoring',
            name='foetus_status',
        ),
        migrations.RemoveField(
            model_name='pregnancymonitoring',
            name='non_prog_reason',
        ),
        migrations.RemoveField(
            model_name='pregnancymonitoring',
            name='pd_status',
        ),
        migrations.RemoveField(
            model_name='pregnancymonitoring',
            name='vet_recommendation',
        ),
    ]
