# Generated by Django 4.2.11 on 2024-07-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0005_remove_pregnancymonitoring_action_to_take_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milkrecord',
            name='employee_name',
        ),
        migrations.AddField(
            model_name='milkrecord',
            name='employee_name',
            field=models.ManyToManyField(default=1, to='portals.employees'),
        ),
    ]
