# Generated by Django 3.1.3 on 2023-02-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0005_auto_20230224_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sick_approach_form',
            name='farmer_username',
            field=models.CharField(choices=[('Ganja Farmer', 'Ganja Farmer'), ('ganja Juana', 'ganja Juana'), ('Jeremiah George', 'Jeremiah George'), ('Febe Hewa', 'Febe Hewa')], max_length=100, verbose_name='Farmer Username'),
        ),
    ]
