# Generated by Django 4.2.14 on 2026-02-12 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0005_remove_movementpermits_date_of_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='movementpermits',
            name='date_of_record',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
