# Generated by Django 4.2.11 on 2024-06-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0006_monthlymilkrecord_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='heatsignmonitoring',
            name='date_of_heat_monitoring',
            field=models.DateField(default='2024-06-18'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pregnancymonitoring',
            name='actual_date_of_delivery',
            field=models.DateField(blank=True, null=True),
        ),
    ]
