# Generated by Django 3.1.3 on 2023-02-25 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_supplierproduct'),
        ('portals', '0006_auto_20230224_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sick_approach_form',
            name='farmer_username',
        ),
        migrations.AddField(
            model_name='sick_approach_form',
            name='farmer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='user.farmer'),
            preserve_default=False,
        ),
    ]
