# Generated by Django 4.2.14 on 2026-02-12 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0006_movementpermits_date_of_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artificialinseminations',
            name='date_of_record',
        ),
        migrations.RemoveField(
            model_name='dailykills',
            name='date_of_record',
        ),
        migrations.RemoveField(
            model_name='diseasereportmov',
            name='date_of_record',
        ),
        migrations.RemoveField(
            model_name='extensionservices',
            name='date_of_record',
        ),
        migrations.RemoveField(
            model_name='noobjections',
            name='date_of_record',
        ),
        migrations.RemoveField(
            model_name='practitioners',
            name='date_of_record',
        ),
        migrations.RemoveField(
            model_name='slaughterhouses',
            name='date_of_record',
        ),
        migrations.RemoveField(
            model_name='vaccinations',
            name='date_of_record',
        ),
    ]
