# Generated by Django 4.2.14 on 2026-02-12 15:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0007_remove_artificialinseminations_date_of_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artificialinseminations',
            name='date_of_record',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailykills',
            name='date_of_record',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diseasereportmov',
            name='date_of_record',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extensionservices',
            name='date_of_record',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noobjections',
            name='date_of_record',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practitioners',
            name='date_of_record',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slaughterhouses',
            name='date_of_record',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccinations',
            name='date_of_record',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
