# Generated by Django 4.2.11 on 2024-07-08 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0008_alter_milkrecord_employee_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milkrecord',
            old_name='employee_name',
            new_name='employee_names',
        ),
    ]
