# Generated by Django 4.2.11 on 2024-06-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0008_alter_calf_breeding_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesofmilk',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
