# Generated by Django 4.2.11 on 2024-07-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0009_alter_salesofmilk_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalsale',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='milkrecord',
            name='time_of_milking',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Noon', 'Noon'), ('Evening', 'Evening')], max_length=10),
        ),
    ]
