# Generated by Django 4.2.14 on 2026-02-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0009_lessonaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='artificialinsemination',
            name='animal_status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
