# Generated by Django 4.2.14 on 2026-03-11 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portals', '0010_artificialinsemination_animal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkcollectioncooler',
            name='location',
            field=models.CharField(default='kericho', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='supply_number',
            field=models.CharField(default=100, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MilkCollectionClerk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('supply_number', models.CharField(max_length=100)),
                ('total_kg_supplied', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='milkcollectioncooler',
            name='clerk_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cooler_record', to='portals.milkcollectionclerk'),
        ),
    ]
