# Generated by Django 4.2.14 on 2026-03-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0011_milkcollectioncooler_location_supplier_supply_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supply_number',
            field=models.CharField(max_length=100),
        ),
    ]
