# Generated by Django 4.2.14 on 2026-03-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0012_alter_supplier_supply_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supply_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
