# Generated by Django 4.2.14 on 2026-05-10 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portals', '0014_fieldquotation_assigned_to_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccinationrecord',
            old_name='mobile_number',
            new_name='reg_no',
        ),
        migrations.RemoveField(
            model_name='vaccinationrecord',
            name='name_of_vet_incharge',
        ),
        migrations.RemoveField(
            model_name='vaccinationrecord',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='vaccinationrecord',
            name='vet_category',
        ),
        migrations.AddField(
            model_name='artificialinsemination',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extensionservice',
            name='assigned_to_official',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_official': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ext_official', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extensionservice',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='vaccination_certificates/'),
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='location',
            field=models.CharField(default='bomet', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='location_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='name_of_animal',
            field=models.CharField(default='chepoit', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='route_administration',
            field=models.CharField(default='skin', max_length=50),
            preserve_default=False,
        ),
    ]
