# Generated by Django 6.0.5 on 2026-05-11 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0015_rename_mobile_number_vaccinationrecord_reg_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseasereport',
            name='vet_in_charge_name',
        ),
        migrations.RemoveField(
            model_name='diseasereport',
            name='vet_mobile_number',
        ),
        migrations.RemoveField(
            model_name='diseasereport',
            name='vet_registration_number',
        ),
    ]
