# Generated by Django 4.2.11 on 2024-07-08 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0015_remove_milkrecord_employee_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkrecord',
            name='employee_names',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='portals.employees'),
        ),
    ]
