# Generated by Django 4.2.11 on 2024-07-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0017_rename_employee_names_milkrecord_employee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinarydrugs',
            name='date_of_purchase',
            field=models.CharField(default='2021-01-01', max_length=40, verbose_name='Date of purchase'),
            preserve_default=False,
        ),
    ]
