# Generated by Django 6.0.5 on 2026-05-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0018_rename_timestamp_payment_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zoommeeting',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='zoommeeting',
            name='access_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
