# Generated by Django 4.2.11 on 2024-07-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0019_alter_veterinarydrugs_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lactatingcow',
            name='cow_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='lactatingcow',
            name='reg_no',
            field=models.CharField(max_length=50),
        ),
    ]
