# Generated by Django 6.0.5 on 2026-05-18 15:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0019_remove_zoommeeting_is_paid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPayment',
            fields=[
            ],
            options={
                'verbose_name': 'Lesson Payment',
                'verbose_name_plural': 'Lesson Payments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('portals.payment',),
        ),
        migrations.CreateModel(
            name='ZoomPayment',
            fields=[
            ],
            options={
                'verbose_name': 'Zoom Payment',
                'verbose_name_plural': 'Zoom Payments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('portals.payment',),
        ),
        migrations.AddField(
            model_name='payment',
            name='user_access_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='zoommeeting',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='blocked_zoom_meetings', to=settings.AUTH_USER_MODEL),
        ),
    ]
