# Generated by Django 4.2.11 on 2024-07-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0021_calf_dam_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='country',
            new_name='county',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='area_of_residence',
        ),
        migrations.AddField(
            model_name='archaricides',
            name='trade_name',
            field=models.CharField(default='almatix', max_length=30, verbose_name='Chemical Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dairyequipment',
            name='model_number',
            field=models.CharField(default='23242', max_length=255, verbose_name='Model Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dairyhygiene',
            name='trade_name',
            field=models.CharField(default='triatix', max_length=255, verbose_name='Trade Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employees',
            name='chief_name',
            field=models.CharField(default='cherongos', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feeds',
            name='quantity_purchased',
            field=models.CharField(default='34kg', max_length=255, verbose_name='Quantity purchased'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feeds',
            name='trade_name',
            field=models.CharField(default='husqavana', max_length=255, verbose_name='Trade Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feeds',
            name='weight',
            field=models.CharField(default=10, max_length=255, verbose_name='Weight'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livestockinsurance',
            name='animal_species',
            field=models.CharField(default='dog', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livestockinsurance',
            name='breed',
            field=models.CharField(default='shephered', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pregnancymonitoring',
            name='repeat_heat_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salaries',
            name='salary_amount',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10, verbose_name='Amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veterinarybills',
            name='amount_billed',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10, verbose_name='Amount'),
            preserve_default=False,
        ),
    ]
