# Generated by Django 4.2.11 on 2024-08-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0022_rename_country_employees_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='chief_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='salaries',
            name='identification',
            field=models.CharField(max_length=255, unique=True, verbose_name='identification'),
        ),
    ]
