# Generated by Django 6.0.5 on 2026-05-29 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0022_alter_cashsales_user_alter_creditsales_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='layerdailyeggproduction',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='egg_productions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
