# Generated by Django 4.2.11 on 2024-08-09 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0023_alter_employees_chief_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veterinarydrugs',
            name='user',
        ),
    ]
