# Generated by Django 6.0.5 on 2026-05-29 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0024_layerfeedrecord_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='layermortalityrecord',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mortality_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='layerfeedrecord',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feed_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
