# Generated by Django 6.0.5 on 2026-05-29 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0025_layermortalityrecord_user_alter_layerfeedrecord_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='layermortalityrecord',
            name='number_of_live_birds',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='layermortalityrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortality_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
