# Generated by Django 4.2.11 on 2024-08-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0026_remove_salaries_identification'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaries',
            name='identification',
            field=models.CharField(default=372466553, max_length=255, unique=True, verbose_name='identification'),
            preserve_default=False,
        ),
    ]
