# Generated by Django 4.2.11 on 2024-08-19 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portals', '0027_salaries_identification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtificialInsemination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cow_name', models.CharField(max_length=255)),
                ('reg_no', models.CharField(max_length=255, unique=True)),
                ('dam_details', models.TextField()),
                ('sire_details', models.TextField()),
                ('previous_calf_gender', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('served_by', models.CharField(choices=[('AI', 'AI'), ('BULL', 'Bull')], max_length=4)),
                ('no_of_repeats', models.IntegerField()),
                ('abortion_status', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('time_of_heat_sign', models.TimeField()),
                ('date_of_heat_sign', models.DateField()),
                ('insemination_time', models.DateTimeField()),
                ('breed_used', models.CharField(max_length=255)),
                ('bull_name', models.CharField(max_length=255)),
                ('bull_reg_no', models.CharField(max_length=255, unique=True)),
                ('semen_source', models.CharField(max_length=255)),
                ('heat_sign_mtr_date', models.DateField()),
                ('repeat_heat_date', models.DateField()),
                ('first_pd_date', models.DateField()),
                ('expected_delivery_date', models.DateField()),
                ('owners_name', models.CharField(max_length=255)),
                ('village', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=15)),
                ('vet_name', models.CharField(max_length=255)),
                ('vet_reg_no', models.CharField(max_length=255, unique=True)),
                ('vet_contact', models.CharField(max_length=15)),
                ('signature', models.ImageField(upload_to='signatures/')),
                ('stamp', models.ImageField(upload_to='stamps/')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deworming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_targeted', models.CharField(choices=[('Cattle', 'Cattle'), ('Sheep', 'Sheep'), ('Goat', 'Goat'), ('Donkey', 'Donkey'), ('Dog', 'Dog'), ('Horse', 'Horse'), ('Poultry', 'Poultry'), ('Other', 'Other')], max_length=10)),
                ('other', models.CharField(blank=True, max_length=255, null=True)),
                ('no_of_adults', models.IntegerField()),
                ('no_of_young_ones', models.IntegerField()),
                ('body_conditions', models.TextField()),
                ('deworming_date', models.DateField()),
                ('drug_of_choice', models.CharField(max_length=255)),
                ('parasites', models.CharField(max_length=255)),
                ('withdrawal_period', models.CharField(max_length=255)),
                ('side_effects', models.TextField(blank=True, null=True)),
                ('nxt_deworming_date', models.DateField()),
                ('farmer_name', models.CharField(max_length=255)),
                ('village', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=15)),
                ('vet_name', models.CharField(max_length=255)),
                ('reg_no', models.CharField(max_length=255, unique=True)),
                ('vet_contact', models.CharField(max_length=15)),
                ('signature', models.ImageField(upload_to='signatures/')),
                ('stamp', models.ImageField(upload_to='stamps/')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FarmConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_of_interest', models.CharField(choices=[('Dairy', 'Dairy'), ('Beef Production', 'Beef Production'), ('Poultry Production', 'Poultry Production'), ('Goat Production', 'Goat Production'), ('Pets', 'Pets'), ('Other', 'Other')], max_length=20)),
                ('other', models.CharField(blank=True, max_length=255, null=True)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('other_area_of_interest', models.CharField(blank=True, max_length=255, null=True)),
                ('give_recommendation', models.TextField(blank=True, null=True)),
                ('manager', models.CharField(max_length=255)),
                ('consultant', models.CharField(max_length=255)),
                ('farmer_name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=15)),
                ('village', models.CharField(max_length=255)),
                ('vet_name', models.CharField(max_length=255)),
                ('vet_reg_no', models.CharField(max_length=255, unique=True)),
                ('vet_contact', models.CharField(max_length=15)),
                ('signature', models.ImageField(upload_to='signatures/')),
                ('stamp', models.ImageField(upload_to='stamps/')),
                ('comment', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PregnancyDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cow_name', models.CharField(max_length=255)),
                ('reg_no', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('Adult', 'Adult'), ('Heifer', 'Heifer')], max_length=10)),
                ('date_of_ai', models.DateField()),
                ('pg_diag_date', models.DateField()),
                ('pd_results', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Not Confirmed', 'Not Confirmed')], max_length=15)),
                ('pd_method', models.CharField(max_length=255)),
                ('positive_pd_months', models.IntegerField(blank=True, null=True)),
                ('negative_pd_comment', models.TextField(blank=True, null=True)),
                ('pd_nxt_date', models.DateField(blank=True, null=True)),
                ('expctd_delivery_date', models.DateField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('owners_name', models.CharField(max_length=255)),
                ('village', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=15)),
                ('vet_name', models.CharField(max_length=255)),
                ('vet_reg_no', models.CharField(max_length=255, unique=True)),
                ('vet_contact', models.CharField(max_length=15)),
                ('signature', models.ImageField(upload_to='signatures/')),
                ('stamp', models.ImageField(upload_to='stamps/')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=255)),
                ('treatment_duration', models.CharField(max_length=255)),
                ('previous_treatment_state', models.TextField()),
                ('prognosis', models.TextField()),
                ('referral_date', models.DateField()),
                ('referral_choice', models.CharField(max_length=255)),
                ('r_vet_name', models.CharField(max_length=255)),
                ('r_vet_contact', models.CharField(max_length=15)),
                ('r_vet_reg_no', models.CharField(max_length=255)),
                ('farmer_name', models.CharField(max_length=255)),
                ('village', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=15)),
                ('vet_name', models.CharField(max_length=255)),
                ('vet_reg_no', models.CharField(max_length=255)),
                ('vet_contact', models.CharField(max_length=15)),
                ('signature', models.ImageField(upload_to='signatures/')),
                ('stamp', models.ImageField(upload_to='stamps/')),
                ('comment', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VeterinaryBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_category', models.CharField(choices=[('Deworming', 'Deworming'), ('Surgery', 'Surgery'), ('AI', 'AI'), ('Clinical', 'Clinical'), ('Vaccination', 'Vaccination'), ('Post Mortem', 'Post Mortem'), ('Pregnancy Diagnosis', 'Pregnancy Diagnosis'), ('Lab Charges', 'Lab Charges')], max_length=20)),
                ('total_amount_billed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode_of_payment', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Mobile Money', 'Mobile Money'), ('Bank Transfer', 'Bank Transfer'), ('Other', 'Other')], max_length=20)),
                ('agreed_date', models.DateField()),
                ('payment_plan', models.TextField(blank=True, null=True)),
                ('farmer_name', models.CharField(max_length=255)),
                ('village', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=15)),
                ('vet_to_be_paid', models.CharField(max_length=255)),
                ('reg_no', models.CharField(max_length=255, unique=True)),
                ('vet_contact', models.CharField(max_length=15)),
                ('signature', models.ImageField(upload_to='signatures/')),
                ('stamp', models.ImageField(upload_to='stamps/')),
                ('comment', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='calf_registration_form',
            name='vet_form',
        ),
        migrations.RemoveField(
            model_name='death_approach_form',
            name='vet_form',
        ),
        migrations.RemoveField(
            model_name='deworming_form',
            name='vet_form',
        ),
        migrations.RemoveField(
            model_name='farm_consultation',
            name='vet_form',
        ),
        migrations.RemoveField(
            model_name='laboratory_form',
            name='vet_form',
        ),
        migrations.RemoveField(
            model_name='livestock_inventory_form',
            name='vet_form',
        ),
        migrations.RemoveField(
            model_name='pregnancy_diagnosis_form',
            name='vet_form',
        ),
        migrations.RemoveField(
            model_name='referral_form',
            name='vet_form',
        ),
        migrations.RemoveField(
            model_name='sick_approach_form',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='sick_approach_form',
            name='vet_form',
        ),
        migrations.RemoveField(
            model_name='surgical_approach_form',
            name='vet_form',
        ),
        migrations.RemoveField(
            model_name='vaccination_form',
            name='vet_form',
        ),
        migrations.RemoveField(
            model_name='veterinary_billing_form',
            name='vet_form',
        ),
        migrations.AlterField(
            model_name='archaricides',
            name='chemical_name',
            field=models.CharField(max_length=50, verbose_name='Chemical Name'),
        ),
        migrations.AlterField(
            model_name='archaricides',
            name='trade_name',
            field=models.CharField(max_length=50, verbose_name='Chemical Name'),
        ),
        migrations.DeleteModel(
            name='Artificial_Insemination_Form',
        ),
        migrations.DeleteModel(
            name='Calf_Registration_Form',
        ),
        migrations.DeleteModel(
            name='Death_Approach_Form',
        ),
        migrations.DeleteModel(
            name='Deworming_Form',
        ),
        migrations.DeleteModel(
            name='Farm_Consultation',
        ),
        migrations.DeleteModel(
            name='Laboratory_Form',
        ),
        migrations.DeleteModel(
            name='Livestock_Inventory_Form',
        ),
        migrations.DeleteModel(
            name='Pregnancy_Diagnosis_Form',
        ),
        migrations.DeleteModel(
            name='Referral_Form',
        ),
        migrations.DeleteModel(
            name='Sick_Approach_Form',
        ),
        migrations.DeleteModel(
            name='Surgical_Approach_Form',
        ),
        migrations.DeleteModel(
            name='Vaccination_Form',
        ),
        migrations.DeleteModel(
            name='Vet_Forms',
        ),
        migrations.DeleteModel(
            name='Veterinary_Billing_Form',
        ),
    ]
