# Generated by Django 6.0.5 on 2026-06-01 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0027_layercullingrecord_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_employment', models.DateField()),
                ('full_name', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=50, unique=True)),
                ('mobile_number', models.CharField(max_length=20)),
                ('next_of_kin_name', models.CharField(max_length=255)),
                ('next_of_kin_contact', models.CharField(max_length=20)),
                ('home_county', models.CharField(max_length=100)),
                ('sub_county', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('area_chief_name', models.CharField(max_length=255)),
                ('chief_contact', models.CharField(max_length=20)),
                ('assigned_department', models.CharField(choices=[('Dairy', 'Dairy'), ('Beef', 'Beef'), ('Goats', 'Goats'), ('Poultry', 'Poultry'), ('Companion Animals', 'Companion Animals')], max_length=50)),
                ('job_position', models.CharField(choices=[('Milker', 'Milker'), ('Cleaner', 'Cleaner'), ('Animal Caretaker', 'Animal Caretaker'), ('Veterinary Officer', 'Veterinary Officer'), ('Driver', 'Driver'), ('Security Officer', 'Security Officer'), ('Farm Manager', 'Farm Manager'), ('Assistant Manager', 'Assistant Manager')], max_length=100)),
                ('mode_of_employment', models.CharField(choices=[('Permanent', 'Permanent'), ('Contract', 'Contract'), ('Casual', 'Casual')], max_length=20)),
                ('agreed_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_period', models.CharField(choices=[('Weekly', 'Weekly'), ('Advance', 'Advance'), ('Monthly', 'Monthly')], max_length=20)),
                ('means_of_payment', models.CharField(choices=[('Cash', 'Cash'), ('Mobile Transfer', 'Mobile Transfer'), ('Bank Account', 'Bank Account')], max_length=50)),
                ('bank_details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employeerecords', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_payment', models.DateField()),
                ('salary_status', models.CharField(choices=[('Casual', 'Casual'), ('Advance Salary', 'Advance Salary'), ('Monthly', 'Monthly')], max_length=30)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_to_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to='portals.employee')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_salary_records', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
