# Generated by Django 6.0.5 on 2026-06-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0029_alter_salaryrecord_employee_alter_salaryrecord_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerecord',
            name='means_of_payment',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Mobile Transfer', 'Mobile Transfer'), ('Bank Account', 'Bank Account'), ('Mpesa', 'Mpesa')], max_length=50),
        ),
        migrations.AlterField(
            model_name='milkrecord',
            name='employee_name',
            field=models.CharField(max_length=100),
        ),
    ]
