# Generated by Django 4.2.11 on 2024-08-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0029_surgicalrecord_sampleprocessing_samplecollection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestockincident',
            name='morbidity_rate',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
