# Generated by Django 6.0.5 on 2026-06-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0030_alter_employeerecord_means_of_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkrecord',
            name='cow_name',
            field=models.CharField(max_length=100),
        ),
    ]
