# Generated by Django 6.0.5 on 2026-06-09 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0031_alter_milkrecord_cow_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livestock',
            options={'verbose_name_plural': 'Livestock'},
        ),
        migrations.RenameField(
            model_name='livestock',
            old_name='date_added',
            new_name='date_of_record',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='animal_type',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='breed_category',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='no_of_adults',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='no_of_animals',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='no_of_dead',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='no_of_females',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='no_of_males',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='no_of_young',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='reason_for_death',
        ),
        migrations.AddField(
            model_name='livestock',
            name='age',
            field=models.CharField(default=10, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livestock',
            name='animal_species',
            field=models.CharField(default='fjjf', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livestock',
            name='breed',
            field=models.CharField(default='ghdh', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livestock',
            name='previous_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='livestock',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livestock',
            name='sex',
            field=models.CharField(default='male', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livestock',
            name='source',
            field=models.CharField(default='kkk', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livestock',
            name='total_number',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livestock',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livestock', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_record', models.DateField()),
                ('asset_category', models.CharField(max_length=100)),
                ('asset_name', models.CharField(max_length=150)),
                ('date_acquired', models.DateField()),
                ('model_number', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('condition', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DrugInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_purchased', models.DateField()),
                ('drug_category', models.CharField(max_length=100)),
                ('drug_name', models.CharField(max_length=150)),
                ('batch_no', models.CharField(max_length=50)),
                ('expiry_date', models.DateField()),
                ('drug_volume', models.CharField(max_length=50)),
                ('quantity_purchased', models.PositiveIntegerField()),
                ('quantity_used', models.PositiveIntegerField(default=0)),
                ('balance', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_of_record_update', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_inventories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Drug Inventories',
            },
        ),
        migrations.CreateModel(
            name='FarmVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_visit', models.DateField()),
                ('visitor_category', models.CharField(max_length=50)),
                ('number_of_visitors', models.PositiveIntegerField()),
                ('county_of_origin', models.CharField(max_length=100)),
                ('objective_of_visits', models.TextField()),
                ('trainings_covered', models.TextField(blank=True, null=True)),
                ('areas_visited', models.CharField(blank=True, max_length=255, null=True)),
                ('training_payment_received', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('reporting_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_visits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeedInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_purchased', models.DateField()),
                ('feed_category', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=150)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity_purchased', models.PositiveIntegerField()),
                ('packed_volume', models.CharField(max_length=50)),
                ('quantity_used', models.PositiveIntegerField(default=0)),
                ('balance', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_of_records_update', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_inventories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
