# Generated by Django 4.2.11 on 2024-08-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0032_rename_farmer_username_postmortemrecord_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laboratoryrecord',
            old_name='signature_and_stamp',
            new_name='vet_signature',
        ),
        migrations.RenameField(
            model_name='samplecollection',
            old_name='signature_and_stamp',
            new_name='vet_signature',
        ),
        migrations.RenameField(
            model_name='sampleprocessing',
            old_name='signature_and_stamp',
            new_name='vet_signature',
        ),
        migrations.RemoveField(
            model_name='surgicalrecord',
            name='signature_and_stamp',
        ),
        migrations.AddField(
            model_name='laboratoryrecord',
            name='stamp_line',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='samplecollection',
            name='stamp_line',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sampleprocessing',
            name='stamp_line',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='surgicalrecord',
            name='stamp_line',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='surgicalrecord',
            name='vet_signature',
            field=models.CharField(default='af', max_length=255),
            preserve_default=False,
        ),
    ]
