# Generated by Django 6.0.5 on 2026-06-09 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0032_alter_livestock_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livestock',
            options={},
        ),
        migrations.RenameField(
            model_name='livestock',
            old_name='date_of_record',
            new_name='date_added',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='age',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='animal_species',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='previous_number',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='source',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='total_number',
        ),
        migrations.AddField(
            model_name='livestock',
            name='animal_type',
            field=models.CharField(choices=[('Cow', 'Cow'), ('Goat', 'Goat'), ('Sheep', 'Sheep'), ('Pig', 'Pig'), ('Chicken', 'Chicken')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='livestock',
            name='breed_category',
            field=models.CharField(choices=[('Dog', [('Labrador Retriever', 'Labrador Retriever'), ('German Shepherd', 'German Shepherd'), ('Golden Retriever', 'Golden Retriever'), ('Bulldog', 'Bulldog'), ('Beagle', 'Beagle'), ('Poodle', 'Poodle'), ('Boxer', 'Boxer'), ('Dachshund', 'Dachshund'), ('Yorkshire Terrier', 'Yorkshire Terrier'), ('Rottweiler', 'Rottweiler')]), ('Cat', [('Siamese', 'Siamese'), ('Persian', 'Persian'), ('Maine Coon', 'Maine Coon'), ('Ragdoll', 'Ragdoll'), ('British Shorthair', 'British Shorthair'), ('Sphynx', 'Sphynx'), ('Bengal', 'Bengal'), ('Abyssinian', 'Abyssinian'), ('Scottish Fold', 'Scottish Fold'), ('Burmese', 'Burmese')]), ('Horse', [('Thoroughbred', 'Thoroughbred'), ('Quarter Horse', 'Quarter Horse'), ('Arabian', 'Arabian'), ('Appaloosa', 'Appaloosa'), ('Paint Horse', 'Paint Horse'), ('Morgan', 'Morgan'), ('Tennessee Walking Horse', 'Tennessee Walking Horse'), ('Friesian', 'Friesian'), ('Pony of the Americas', 'Pony of the Americas'), ('Miniature Horse', 'Miniature Horse')]), ('Cattle', [('Angus', 'Angus'), ('Hereford', 'Hereford'), ('Charolais', 'Charolais'), ('Simmental', 'Simmental'), ('Limousin', 'Limousin'), ('Texas Longhorn', 'Texas Longhorn'), ('Holstein', 'Holstein'), ('Jersey', 'Jersey'), ('Gelbvieh', 'Gelbvieh'), ('Brahman', 'Brahman')]), ('Sheep', [('Merino', 'Merino'), ('Dorper', 'Dorper'), ('Suffolk', 'Suffolk'), ('Rambouillet', 'Rambouillet'), ('Hampshire', 'Hampshire'), ('Shropshire', 'Shropshire'), ('Dorset', 'Dorset'), ('Cotswold', 'Cotswold'), ('Lincoln', 'Lincoln'), ('Targhee', 'Targhee')]), ('Goat', [('Boer', 'Boer'), ('Nubian', 'Nubian'), ('Saanen', 'Saanen'), ('Angora', 'Angora'), ('LaMancha', 'LaMancha'), ('Alpine', 'Alpine'), ('Toggenburg', 'Toggenburg'), ('Kiko', 'Kiko'), ('Spanish', 'Spanish'), ('Pygmy', 'Pygmy')])], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='livestock',
            name='comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='livestock',
            name='no_of_adults',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='livestock',
            name='no_of_animals',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='livestock',
            name='no_of_dead',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='livestock',
            name='no_of_females',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='livestock',
            name='no_of_males',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='livestock',
            name='no_of_young',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='livestock',
            name='reason_for_death',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LivestockInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_species', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('total_number', models.PositiveIntegerField()),
                ('previous_number', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(max_length=150)),
                ('date_of_record', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livestock_inventory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Livestock',
            },
        ),
    ]
