# Generated by Django 4.2.11 on 2024-08-22 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portals', '0033_rename_signature_and_stamp_laboratoryrecord_vet_signature_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccinationrecord',
            old_name='animal_species_targeted',
            new_name='species_targeted',
        ),
        migrations.AlterField(
            model_name='postmortemrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='sex_of_animal',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
