# Generated by Django 6.0.5 on 2026-06-13 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0033_alter_livestock_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailykill',
            name='price_per_head',
            field=models.PositiveIntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='druginventory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='drug_inventories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='farmvisit',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='farm_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedinventory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feed_inventories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='livestockinventory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='livestock_inventory', to=settings.AUTH_USER_MODEL),
        ),
    ]
