# Generated by Django 6.0.5 on 2026-06-13 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0034_dailykill_price_per_head_alter_asset_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='livestockregistration',
            name='assigned_to',
            field=models.ForeignKey(default=1, limit_choices_to={'is_vet_officer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='livestock_reg', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
