# Generated by Django 4.2.11 on 2024-08-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0034_rename_animal_species_targeted_vaccinationrecord_species_targeted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmortemrecord',
            name='signature_and_stamp',
        ),
        migrations.RemoveField(
            model_name='samplecollection',
            name='vet_signature',
        ),
        migrations.RemoveField(
            model_name='surgicalrecord',
            name='vet_signature',
        ),
        migrations.RemoveField(
            model_name='vaccinationrecord',
            name='vet_signature',
        ),
        migrations.AddField(
            model_name='postmortemrecord',
            name='signature',
            field=models.ImageField(default='dfergfrf', upload_to='signatures/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postmortemrecord',
            name='stamp',
            field=models.ImageField(default='efwe', upload_to='stamps/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samplecollection',
            name='signature',
            field=models.ImageField(default='sfdsd', upload_to='signatures/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surgicalrecord',
            name='signature',
            field=models.ImageField(default='dsjfr', upload_to='signatures/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='signature',
            field=models.ImageField(default='dsfsfg', upload_to='signatures/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='samplecollection',
            name='stamp_line',
            field=models.ImageField(default='gergr', upload_to='stamps/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='surgicalrecord',
            name='stamp_line',
            field=models.ImageField(default='dsfrf', upload_to='stamps/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='stamp_line',
            field=models.ImageField(default='asdef', upload_to='stamps/'),
            preserve_default=False,
        ),
    ]
