# Generated by Django 6.0.5 on 2026-06-15 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0036_feedingrecord_fish_growthmonitoring_mortalityrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedingrecord',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fish_feeding_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fish',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fish_stocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='growthmonitoring',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fish_growth_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mortalityrecord',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fish_mortality_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
