# Generated by Django 4.2.11 on 2024-08-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0036_rename_vet_signature_laboratoryrecord_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='signature',
            field=models.ImageField(upload_to='portals/media/signatures/'),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='stamp',
            field=models.ImageField(upload_to='portals/media/stamps/'),
        ),
    ]
