# Generated by Django 6.0.5 on 2026-06-15 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0037_alter_feedingrecord_user_alter_fish_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 15, 18, 44, 24, 372827, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorial',
            name='stop',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 15, 18, 44, 51, 239353, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
