# Generated by Django 6.0.5 on 2026-06-22 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0038_tutorial_start_tutorial_stop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surgicalrecord',
            name='practitioner',
        ),
        migrations.RemoveField(
            model_name='surgicalrecord',
            name='vet_category',
        ),
        migrations.RemoveField(
            model_name='surgicalrecord',
            name='vet_mobile_number',
        ),
    ]
