# Generated by Django 6.0.5 on 2026-06-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0039_remove_surgicalrecord_practitioner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationrecord',
            name='manufacturer',
            field=models.CharField(default='syngenta', max_length=50),
            preserve_default=False,
        ),
    ]
