# Generated by Django 6.0.5 on 2026-06-25 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0040_vaccinationrecord_manufacturer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinationrecord',
            name='village_vaccination_done',
        ),
        migrations.AlterField(
            model_name='diseasereport',
            name='assigned_to_official',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_official': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disease_report', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='diseasereport',
            name='sample_taken_to_lab',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
    ]
