# Generated by Django 4.2.11 on 2024-08-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0040_alter_artificialinsemination_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgicalrecord',
            name='prognosis_of_patient',
            field=models.CharField(choices=[('Good', 'Good'), ('Fair', 'Fair'), ('Grave', 'Grave')], max_length=15),
        ),
    ]
