# Generated by Django 6.0.5 on 2026-06-26 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0042_remove_abortionrecord_vet_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artificialinsemination',
            name='vet_category',
        ),
        migrations.RemoveField(
            model_name='artificialinsemination',
            name='vet_contact',
        ),
        migrations.RemoveField(
            model_name='artificialinsemination',
            name='vet_name',
        ),
        migrations.RemoveField(
            model_name='artificialinsemination',
            name='vet_reg_no',
        ),
        migrations.RemoveField(
            model_name='deworming',
            name='reg_no',
        ),
        migrations.RemoveField(
            model_name='deworming',
            name='vet_category',
        ),
        migrations.RemoveField(
            model_name='deworming',
            name='vet_contact',
        ),
        migrations.RemoveField(
            model_name='deworming',
            name='vet_name',
        ),
        migrations.RemoveField(
            model_name='farmconsultation',
            name='vet_category',
        ),
        migrations.RemoveField(
            model_name='farmconsultation',
            name='vet_contact',
        ),
        migrations.RemoveField(
            model_name='farmconsultation',
            name='vet_name',
        ),
        migrations.RemoveField(
            model_name='farmconsultation',
            name='vet_reg_no',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='vet_category',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='vet_contact',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='vet_name',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='vet_reg_no',
        ),
    ]
