# Generated by Django 6.0.5 on 2026-06-26 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0044_routinemanagement_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routinemanagement',
            name='assigned_to',
        ),
    ]
