# Generated by Django 4.2.11 on 2024-09-02 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0046_surgicalrecord_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surgicalrecord',
            name='assigned_to',
        ),
    ]
