# Generated by Django 6.0.5 on 2026-07-02 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0046_routinemanagement_assigned_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='veterinaryeprescription',
            old_name='manufacturing_company',
            new_name='dosage',
        ),
        migrations.RenameField(
            model_name='veterinaryeprescription',
            old_name='pharmacy_name',
            new_name='name_of_the_buyer',
        ),
        migrations.RenameField(
            model_name='veterinaryeprescription',
            old_name='vets_comments',
            new_name='vet_pharmacist_comment',
        ),
        migrations.RemoveField(
            model_name='veterinaryeprescription',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='veterinaryeprescription',
            name='buyer_category',
        ),
        migrations.RemoveField(
            model_name='veterinaryeprescription',
            name='buyer_name',
        ),
        migrations.RemoveField(
            model_name='veterinaryeprescription',
            name='buyer_signature',
        ),
        migrations.RemoveField(
            model_name='veterinaryeprescription',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='veterinaryeprescription',
            name='drug_dosage',
        ),
        migrations.RemoveField(
            model_name='veterinaryeprescription',
            name='kvb_no',
        ),
        migrations.RemoveField(
            model_name='veterinaryeprescription',
            name='licence_no',
        ),
        migrations.RemoveField(
            model_name='veterinaryeprescription',
            name='livestock_type',
        ),
        migrations.RemoveField(
            model_name='veterinaryeprescription',
            name='location',
        ),
        migrations.RemoveField(
            model_name='veterinaryeprescription',
            name='route_of_administration',
        ),
        migrations.RemoveField(
            model_name='veterinaryeprescription',
            name='sign',
        ),
        migrations.RemoveField(
            model_name='veterinaryeprescription',
            name='signed_on',
        ),
        migrations.RemoveField(
            model_name='veterinaryeprescription',
            name='vet_practitioner_incharge',
        ),
        migrations.AddField(
            model_name='veterinaryeprescription',
            name='animal_species',
            field=models.CharField(default='gfdiu', help_text='e.g., Cattle, Goat, Sheep', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veterinaryeprescription',
            name='batch_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='veterinaryeprescription',
            name='buyer_contact',
            field=models.CharField(blank=True, max_length=100, verbose_name='Contact'),
        ),
        migrations.AddField(
            model_name='veterinaryeprescription',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='veterinaryeprescription',
            name='signature_and_stamp',
            field=models.CharField(blank=True, help_text='Verification string or signature link', max_length=200),
        ),
        migrations.AlterField(
            model_name='routinemanagement',
            name='user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='veterinaryeprescription',
            name='age',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='veterinaryeprescription',
            name='breed',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='veterinaryeprescription',
            name='buyer_kvb_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='K.V.B No.'),
        ),
        migrations.AlterField(
            model_name='veterinaryeprescription',
            name='buyer_licence_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='Licence No.'),
        ),
        migrations.AlterField(
            model_name='veterinaryeprescription',
            name='clinical_use',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='veterinaryeprescription',
            name='drug_category',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II')], max_length=3),
        ),
        migrations.AlterField(
            model_name='veterinaryeprescription',
            name='drug_trade_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='veterinaryeprescription',
            name='drug_volume',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='veterinaryeprescription',
            name='duration_of_treatment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='veterinaryeprescription',
            name='prescription_target',
            field=models.CharField(choices=[('vet_surgeon', 'Vet Surgeon'), ('para_professional', 'Para-Professional')], max_length=30),
        ),
        migrations.AlterField(
            model_name='veterinaryeprescription',
            name='quantity_purchased',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='veterinaryeprescription',
            name='side_effect',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='veterinaryeprescription',
            name='withdrawal_period',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
