# Generated by Django 4.2.11 on 2024-09-02 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portals', '0047_remove_surgicalrecord_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgicalrecord',
            name='assigned_to',
            field=models.ForeignKey(default=2, limit_choices_to={'is_farmer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_records', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
