# Generated by Django 4.2.11 on 2024-09-02 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portals', '0048_surgicalrecord_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='artificialinsemination',
            name='assigned_to',
            field=models.ForeignKey(default=2, limit_choices_to={'is_farmer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='ai_records', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deworming',
            name='assigned_to',
            field=models.ForeignKey(default=2, limit_choices_to={'is_farmer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='deworming_records', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmconsultation',
            name='assigned_to',
            field=models.ForeignKey(default=2, limit_choices_to={'is_farmer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='consultation_records', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laboratoryrecord',
            name='assigned_to',
            field=models.ForeignKey(default=2, limit_choices_to={'is_farmer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='lab_records', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livestockincident',
            name='assigned_to',
            field=models.ForeignKey(default=2, limit_choices_to={'is_farmer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='incidence_records', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postmortemrecord',
            name='assigned_to',
            field=models.ForeignKey(default=2, limit_choices_to={'is_farmer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='postmortem_records', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pregnancydiagnosis',
            name='assigned_to',
            field=models.ForeignKey(default=2, limit_choices_to={'is_farmer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='pregdiagnosis_records', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referral',
            name='assigned_to',
            field=models.ForeignKey(default=2, limit_choices_to={'is_farmer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='referral_records', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samplecollection',
            name='assigned_to',
            field=models.ForeignKey(default=2, limit_choices_to={'is_farmer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='collection_records', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sampleprocessing',
            name='assigned_to',
            field=models.ForeignKey(default=2, limit_choices_to={'is_farmer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='processing_records', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='assigned_to',
            field=models.ForeignKey(default=2, limit_choices_to={'is_farmer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veterinarybilling',
            name='assigned_to',
            field=models.ForeignKey(default=2, limit_choices_to={'is_farmer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='vet_billing_records', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='surgicalrecord',
            name='assigned_to',
            field=models.ForeignKey(limit_choices_to={'is_farmer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='surgical_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='surgicalrecord',
            name='user',
            field=models.ForeignKey(default=1, limit_choices_to={'is_vet_officer': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
