# Generated by Django 4.2.11 on 2024-09-05 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portals', '0049_artificialinsemination_assigned_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_species_affected', models.CharField(choices=[('Cattle', 'Cattle'), ('Sheep', 'Sheep'), ('Goat', 'Goat'), ('Donkey', 'Donkey'), ('Dog', 'Dog'), ('Cat', 'Cat'), ('Horse', 'Horse'), ('Poultry', 'Poultry'), ('Other', 'Other')], max_length=20)),
                ('other_species', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_animals_sick', models.PositiveIntegerField()),
                ('name_of_animal_affected', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=100)),
                ('age_of_animal', models.PositiveIntegerField()),
                ('breed_of_animal', models.CharField(max_length=100)),
                ('nature_of_disease', models.CharField(choices=[('Acute', 'Acute'), ('Sub-acute', 'Sub-acute'), ('Chronic', 'Chronic')], max_length=20)),
                ('clinical_signs', models.TextField()),
                ('differential_diagnosis', models.TextField()),
                ('final_diagnosis', models.TextField()),
                ('case_history', models.TextField()),
                ('treatment_plan', models.TextField()),
                ('drugs_of_choice', models.TextField()),
                ('prognosis', models.TextField()),
                ('date_of_start_dose', models.DateField()),
                ('final_treatment_date', models.DateField(blank=True, null=True)),
                ('is_zoonotic', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('precautions', models.TextField(blank=True, null=True)),
                ('refer_case_to_other_vet', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('is_disease_reportable', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('reason_if_not_reportable', models.TextField(blank=True, null=True)),
                ('is_disease_notifiable', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('notified_authority', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('comment', models.TextField(blank=True, null=True)),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_village', models.CharField(max_length=100)),
                ('owner_contact', models.CharField(max_length=15)),
                ('vet_in_charge_name', models.CharField(max_length=100)),
                ('vet_registration_number', models.CharField(max_length=100)),
                ('vet_contact', models.CharField(max_length=15)),
                ('vet_signature', models.CharField(max_length=100)),
                ('rubber_stamp', models.CharField(blank=True, max_length=100, null=True)),
                ('assigned_to', models.ForeignKey(limit_choices_to={'is_farmer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_records', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
