# Generated by Django 4.2.11 on 2024-09-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0050_clinicalrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artificialinsemination',
            name='vet_reg_no',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='deworming',
            name='reg_no',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='farmconsultation',
            name='vet_reg_no',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pregnancydiagnosis',
            name='vet_reg_no',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='veterinarybilling',
            name='reg_no',
            field=models.CharField(max_length=255),
        ),
    ]
