# Generated by Django 4.2.11 on 2024-09-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0052_diary_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='artificialinsemination',
            name='insemination_date',
            field=models.DateField(default='2024-7-9'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artificialinsemination',
            name='insemination_status',
            field=models.CharField(choices=[('First', 'First'), ('Repeat', 'Repeat')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
