# Generated by Django 4.2.11 on 2024-09-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0053_artificialinsemination_insemination_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artificialinsemination',
            name='insemination_time',
            field=models.TimeField(),
        ),
    ]
