# Generated by Django 4.2.11 on 2024-09-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0057_alter_artificialinsemination_vet_reg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artificialinsemination',
            name='bull_reg_no',
            field=models.CharField(max_length=255),
        ),
    ]
