# Generated by Django 4.2.11 on 2024-09-28 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portals', '0058_alter_artificialinsemination_bull_reg_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livestock_category', models.CharField(choices=[('cattle', 'Cattle'), ('sheep', 'Sheep'), ('goat', 'Goat'), ('donkey', 'Donkey'), ('dog', 'Dog'), ('cat', 'Cat'), ('poultry', 'Poultry'), ('none', 'None')], max_length=20)),
                ('other_livestock_category', models.CharField(blank=True, max_length=50, null=True)),
                ('number_of_animals_affected', models.IntegerField()),
                ('sex_of_animals_affected', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('both', 'Both Female and Male')], max_length=10)),
                ('age_of_animals_affected', models.CharField(choices=[('adult', 'Adult'), ('young', 'Young'), ('all', 'All')], max_length=10)),
                ('clinical_signs', models.TextField()),
                ('number_of_dead_animals', models.IntegerField()),
                ('propose_control_measures', models.TextField()),
                ('sample_taken_to_lab', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('tentative_diagnosis', models.TextField()),
                ('village_disease_occurred', models.CharField(max_length=100)),
                ('sub_county', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_mobile_number', models.CharField(max_length=20)),
                ('vet_in_charge_name', models.CharField(max_length=100)),
                ('vet_registration_number', models.CharField(max_length=50)),
                ('vet_mobile_number', models.CharField(max_length=20)),
                ('signature', models.TextField(blank=True, null=True)),
                ('stamp', models.TextField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(limit_choices_to={'is_farmer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='disease_report', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
