# Generated by Django 4.2.11 on 2024-10-02 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0059_diseasereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Butcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('medical_license_status', models.BooleanField(default=False)),
                ('livestock_slaughtered', models.IntegerField()),
                ('meat_container_number', models.CharField(max_length=50)),
                ('meat_carrier_number', models.CharField(max_length=50)),
                ('means_of_transport', models.CharField(choices=[('motorbike', 'Motorbike'), ('vehicle', 'Vehicle')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_to', models.CharField(choices=[('farmer', 'Farmer'), ('company', 'Company')], max_length=50)),
                ('invoice_category', models.CharField(choices=[('Deworming', 'Deworming'), ('Surgery', 'Surgery'), ('AI', 'Artificial Insemination'), ('Clinical', 'Clinical'), ('Vaccination', 'Vaccination'), ('Post Mortem', 'Post Mortem'), ('Pregnancy Diagnosis', 'Pregnancy Diagnosis'), ('Lab Charges', 'Lab Charges'), ('Farm Consultation', 'Farm Consultation'), ('Visit', 'Visit')], max_length=50)),
                ('date_of_invoice', models.DateField()),
                ('total_amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('farmer_name', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('vet_in_charge_of_invoice', models.CharField(max_length=100)),
                ('vet_registration_number', models.CharField(max_length=100)),
                ('vet_contact', models.CharField(max_length=15)),
                ('signature', models.CharField(blank=True, max_length=100, null=True)),
                ('stamp', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slaughterhouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('county', models.CharField(max_length=255)),
                ('sub_county', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('slaughterhouse_category', models.CharField(choices=[('small_scale', 'Small Scale'), ('large_scale', 'Large Scale')], max_length=50)),
                ('livestock_slaughtered', models.IntegerField()),
                ('number_of_employees', models.IntegerField()),
                ('roller_mark_number', models.CharField(max_length=50)),
                ('inspector_name', models.CharField(max_length=255)),
                ('inspector_registration_number', models.CharField(max_length=100)),
                ('inspector_employment_number', models.CharField(max_length=100)),
                ('inspector_mobile_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('position', models.CharField(choices=[('flager', 'Flager'), ('cleaner', 'Cleaner'), ('supervisor', 'Supervisor'), ('security_officer', 'Security Officer')], max_length=50)),
                ('medical_license_status', models.BooleanField(default=False)),
                ('slaughterhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='portals.slaughterhouse')),
            ],
        ),
    ]
