# Generated by Django 4.2.11 on 2024-10-03 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portals', '0060_butcher_invoice_slaughterhouse_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseasereport',
            name='assigned_to',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='assigned_to',
            field=models.ForeignKey(limit_choices_to={'is_farmer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='disease_report', to=settings.AUTH_USER_MODEL),
        ),
    ]
