# Generated by Django 4.2.11 on 2024-10-03 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portals', '0061_remove_diseasereport_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='butcher',
            name='medical_license_status',
            field=models.BooleanField(max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='assigned_to',
            field=models.ForeignKey(limit_choices_to={'is_farmer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_report', to=settings.AUTH_USER_MODEL),
        ),
    ]
