# Generated by Django 4.2.11 on 2024-10-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0062_alter_butcher_medical_license_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='butcher',
            name='medical_license_status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='medical_license_status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='slaughterhouse',
            field=models.CharField(max_length=60),
        ),
    ]
