# Generated by Django 4.2.11 on 2024-10-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0063_alter_butcher_medical_license_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyKill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('livestock_category', models.CharField(choices=[('Cattle', 'Cattle'), ('Sheep', 'Sheep'), ('Goat', 'Goat'), ('Pig', 'Pig')], max_length=50)),
                ('number_of_females_killed', models.PositiveIntegerField()),
                ('number_of_males_killed', models.PositiveIntegerField()),
                ('total_kills_per_day', models.PositiveIntegerField()),
                ('condemnation_done', models.BooleanField(default=False)),
                ('condemnation_status', models.CharField(blank=True, choices=[('Local Condemnation', 'Local Condemnation'), ('Carcass Condemnation', 'Carcass Condemnation')], max_length=50, null=True)),
                ('comment_by_inspector', models.TextField(blank=True, null=True)),
                ('inspector_name', models.CharField(max_length=100)),
                ('inspector_reg_number', models.CharField(max_length=50)),
                ('inspector_status', models.CharField(choices=[('Employed', 'Employed'), ('Delegated', 'Delegated'), ('Intern/Student', 'Intern/Student')], max_length=50)),
            ],
        ),
    ]
