# Generated by Django 4.2.11 on 2024-10-25 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0067_choice_question_useranswer_choice_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='time_of_event',
            field=models.TimeField(default=datetime.datetime(2024, 10, 25, 12, 14, 10, 367451, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
