# Generated by Django 4.2.11 on 2024-11-05 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0070_remove_artificialinsemination_assigned_to_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artificialinsemination',
            old_name='farmer_name',
            new_name='farm_name',
        ),
    ]
