# Generated by Django 4.2.11 on 2024-11-05 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portals', '0071_rename_farmer_name_artificialinsemination_farm_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='artificialinsemination',
            name='assigned_to',
            field=models.ForeignKey(default=1, limit_choices_to={'is_farmer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='ai_records', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
