# Generated by Django 4.2.11 on 2024-11-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0072_artificialinsemination_assigned_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='title',
            new_name='lesson',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='description',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='kvb_number',
            field=models.CharField(default=5555, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorial',
            name='points',
            field=models.CharField(default=20, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorial',
            name='url',
            field=models.URLField(default='localhost/points'),
            preserve_default=False,
        ),
    ]
