# Generated by Django 4.2.11 on 2024-11-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0074_tutorial_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='unit_price',
            field=models.CharField(default=40, max_length=5),
            preserve_default=False,
        ),
    ]
