# Generated by Django 4.2.11 on 2024-11-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0076_rename_tutorial_section_lesson_tutorial_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='points',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
