# Generated by Django 4.2.11 on 2024-11-12 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0080_questions_rename_question_text_question_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='is_multiple_choice',
        ),
        migrations.AlterField(
            model_name='choices',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='portals.questions'),
        ),
    ]
