# Generated by Django 4.2.11 on 2024-11-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0082_rename_choices_cpdchoices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='file',
            field=models.FileField(default='users/file.pdf', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
