# Generated by Django 3.1.3 on 2024-11-19 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0086_cpdquestions_tutorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpdquestions',
            name='tutorial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='portals.tutorial'),
        ),
    ]
