# Generated by Django 3.1.3 on 2024-11-19 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0093_auto_20241119_0639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpdquestions',
            name='tutorial',
        ),
        migrations.AddField(
            model_name='cpdquestions',
            name='section',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='portals.section'),
            preserve_default=False,
        ),
    ]
