# Generated by Django 3.1.3 on 2024-11-20 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0096_auto_20241119_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='portals.section'),
            preserve_default=False,
        ),
    ]
