# Generated by Django 3.1.3 on 2024-11-20 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0097_quizresult_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='section',
        ),
    ]
