# Generated by Django 3.1.3 on 2024-11-20 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0098_remove_quizresult_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='section',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='portals.section'),
            preserve_default=False,
        ),
    ]
