# Generated by Django 3.1.3 on 2024-11-21 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0099_quizresult_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='kvb_number',
            new_name='cpd_number',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='url',
        ),
    ]
