# Generated by Django 3.1.3 on 2024-11-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0101_auto_20241121_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='artificialinsemination',
            name='semen_type',
            field=models.CharField(choices=[('Conventional', 'Conventional'), ('Sexed', 'Sexed')], default='sexed', max_length=20),
            preserve_default=False,
        ),
    ]
