# Generated by Django 3.1.3 on 2024-11-28 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portals', '0102_artificialinsemination_semen_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalvingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_calving', models.DateField()),
                ('insemination_date', models.DateField(blank=True, null=True)),
                ('days_to_calving_down', models.PositiveIntegerField(help_text='Number of days to calving down')),
                ('cow_name', models.CharField(max_length=100)),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('calving_procedure', models.CharField(choices=[('Normal', 'Normal'), ('Assisted', 'Assisted'), ('C-Section', 'C-Section')], max_length=20)),
                ('rab_status', models.CharField(choices=[('Natural Expulsion', 'Natural Expulsion'), ('Manual Removal', 'Manual Removal')], max_length=20)),
                ('hours_for_natural_expulsion', models.PositiveIntegerField()),
                ('calf_sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('calf_status', models.CharField(choices=[('Live', 'Live'), ('Dead', 'Dead')], max_length=10)),
                ('reason_for_dead_foetus', models.CharField(blank=True, choices=[('Delayed Labour', 'Delayed Labour'), ('Breech Presentation', 'Breech Presentation'), ('None', 'None')], max_length=50, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LivestockExaminationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livestock_category', models.CharField(choices=[('Cattle', 'Cattle'), ('Sheep', 'Sheep'), ('Goat', 'Goat'), ('Poultry', 'Poultry'), ('None', 'None')], max_length=50)),
                ('other_category', models.CharField(blank=True, max_length=100, null=True)),
                ('age_of_animal', models.PositiveIntegerField()),
                ('breed', models.CharField(max_length=100)),
                ('sex_of_animal', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('number_of_animals', models.PositiveIntegerField()),
                ('origin_of_animal', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('reason_for_examination', models.CharField(choices=[('Slaughter', 'Slaughter'), ('Breeding', 'Breeding'), ('Culling', 'Culling'), ('Disease Control', 'Disease Control'), ('For Sale', 'For Sale')], max_length=50)),
                ('recommendation', models.TextField()),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_mobile_number', models.CharField(max_length=15)),
                ('veterinary_officer_in_charge', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=50)),
                ('veterinary_officer_mobile_number', models.CharField(max_length=15)),
                ('veterinary_officer_signature', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
