# Generated by Django 3.1.3 on 2024-11-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0103_calvingrecord_livestockexaminationrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livestock_category', models.CharField(choices=[('Cattle', 'Cattle'), ('Sheep', 'Sheep'), ('Goat', 'Goat'), ('Dog', 'Dog'), ('Cat', 'Cat'), ('Horse', 'Horse'), ('None', 'None')], max_length=20)),
                ('other_category', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_assessment', models.DateField()),
                ('name_of_animal', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=50)),
                ('color_of_animal', models.CharField(max_length=50)),
                ('age_of_animal', models.PositiveIntegerField()),
                ('sex_of_animal', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('number_of_animals', models.PositiveIntegerField()),
                ('origin_of_animal', models.CharField(max_length=100)),
                ('place_of_assessment', models.CharField(choices=[('Farm', 'Farm'), ('Market', 'Market')], max_length=20)),
                ('destination', models.CharField(max_length=100)),
                ('reason_for_assessment', models.CharField(choices=[('Slaughter', 'Slaughter'), ('Breeding', 'Breeding'), ('Culling', 'Culling'), ('Disease Control', 'Disease Control'), ('Sales', 'Sales'), ('For Complaint', 'For Complaint'), ('Theft Cases', 'Theft Cases'), ('For Export', 'For Export')], max_length=50)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('owner_of_animal', models.CharField(max_length=100)),
                ('owner_mobile_number', models.CharField(max_length=15)),
                ('veterinary_practitioner_in_charge', models.CharField(max_length=100)),
                ('practitioner_registration_number', models.CharField(max_length=50)),
                ('practitioner_contact', models.CharField(max_length=15)),
                ('signature_and_stamp', models.ImageField(upload_to='signatures_and_stamps/')),
            ],
        ),
    ]
