# Generated by Django 3.1.3 on 2024-12-03 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portals', '0106_auto_20241129_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailykill',
            name='assigned_to',
            field=models.ForeignKey(default=1, limit_choices_to={'is_farmer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='kills', to='user.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailykill',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
