# Generated by Django 3.1.3 on 2024-12-15 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0110_slaughterhouse_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movementpermit',
            name='assigned_to',
        ),
    ]
