# Generated by Django 3.1.3 on 2024-12-15 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portals', '0111_remove_movementpermit_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='movementpermit',
            name='assigned_to',
            field=models.ForeignKey(default=1, limit_choices_to={'is_farmer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='movement_permit', to=settings.AUTH_USER_MODEL),
        ),
    ]
