# Generated by Django 3.1.3 on 2024-12-15 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portals', '0112_movementpermit_assigned_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practitioner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('subcounty', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=100)),
                ('area_of_operation', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=10)),
                ('vet_category', models.CharField(max_length=10)),
                ('registration_number', models.CharField(max_length=30)),
                ('assigned_to', models.ForeignKey(default=1, limit_choices_to={'is_farmer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='practitioner_record', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
