# Generated by Django 3.1.3 on 2024-12-16 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0114_auto_20241216_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationrecord',
            name='dosage',
            field=models.CharField(default='mililiters', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='expiry_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
