# Generated by Django 3.1.3 on 2024-12-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0115_auto_20241216_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationrecord',
            name='other_disease',
            field=models.CharField(default='malaria', max_length=255),
            preserve_default=False,
        ),
    ]
