# Generated by Django 3.1.3 on 2024-12-16 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portals', '0116_vaccinationrecord_other_disease'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessmentrecord',
            old_name='assigned_to',
            new_name='assigned_to_official',
        ),
        migrations.RemoveField(
            model_name='dailykill',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='diseasereport',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='monthlyreport',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='movementpermit',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='noobjection',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='practitioner',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='artificialinsemination',
            name='assigned_to_official',
            field=models.ForeignKey(blank=True, default=1, limit_choices_to={'is_official': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_official', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailykill',
            name='assigned_to_official',
            field=models.ForeignKey(default=1, limit_choices_to={'is_official': True}, on_delete=django.db.models.deletion.CASCADE, related_name='kills', to='user.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diseasereport',
            name='assigned_to_official',
            field=models.ForeignKey(default=1, limit_choices_to={'is_official': True}, on_delete=django.db.models.deletion.CASCADE, related_name='disease_report', to='user.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livestockexaminationrecord',
            name='assigned_to_official',
            field=models.ForeignKey(default=1, limit_choices_to={'is_official': True}, on_delete=django.db.models.deletion.CASCADE, related_name='examination_report', to='user.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='assigned_to_official',
            field=models.ForeignKey(blank=True, default=1, limit_choices_to={'is_official': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_reports_official', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movementpermit',
            name='assigned_to_official',
            field=models.ForeignKey(default=1, limit_choices_to={'is_official': True}, on_delete=django.db.models.deletion.CASCADE, related_name='movement_permit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noobjection',
            name='assigned_to_official',
            field=models.ForeignKey(default=1, limit_choices_to={'is_official': True}, on_delete=django.db.models.deletion.CASCADE, related_name='noobjection_form', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='assigned_to_official',
            field=models.ForeignKey(default=1, limit_choices_to={'is_official': True}, on_delete=django.db.models.deletion.CASCADE, related_name='practitioner_record', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='slaughterhouse',
            name='assigned_to_official',
            field=models.ForeignKey(default=1, limit_choices_to={'is_official': True}, on_delete=django.db.models.deletion.CASCADE, related_name='slaughter_house', to='user.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='assigned_to_official',
            field=models.ForeignKey(blank=True, default=1, limit_choices_to={'is_official': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccination_official', to=settings.AUTH_USER_MODEL),
        ),
    ]
