# Generated by Django 3.1.3 on 2024-12-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0124_auto_20241229_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='artificialinsemination',
            name='provided_by',
            field=models.CharField(default='kirui', max_length=255),
            preserve_default=False,
        ),
    ]
