# Generated by Django 3.1.3 on 2024-12-29 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0125_artificialinsemination_provided_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artificialinsemination',
            old_name='signature',
            new_name='signature_stamp',
        ),
        migrations.RemoveField(
            model_name='artificialinsemination',
            name='stamp',
        ),
    ]
