# Generated by Django 3.1.3 on 2024-12-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0126_auto_20241229_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinationrecord',
            name='stamp',
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='sub_county',
            field=models.CharField(default='kericho', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='ward',
            field=models.CharField(default='klerh', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='sex_of_animal',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('All', 'All')], max_length=10),
        ),
    ]
