# Generated by Django 3.1.3 on 2024-12-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0127_auto_20241229_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='vaccination_of',
            field=models.CharField(choices=[('anthrax', 'Anthrax'), ('fmd', 'FMD'), ('lumpy_skin_disease', 'Lumpy Skin Disease'), ('rift_valley_fever', 'Rift Valley Fever'), ('rabies', 'Rabies'), ('cbpp', 'CBPP '), ('ccpp', 'CCPP '), ('ppr', 'PPR '), ('newcastle_disease', 'Newcastle Disease'), ('canine_distemper', 'Canine Distemper'), ('none', 'None')], max_length=20),
        ),
    ]
