# Generated by Django 3.1.3 on 2024-12-29 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portals', '0128_auto_20241229_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailykill',
            name='assigned_to',
            field=models.ForeignKey(blank=True, default=1, limit_choices_to={'is_farmer': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kills_assign', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailykill',
            name='assigned_to_official',
            field=models.ForeignKey(blank=True, default=1, limit_choices_to={'is_official': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kills_official', to=settings.AUTH_USER_MODEL),
        ),
    ]
