# Generated by Django 3.1.3 on 2024-12-29 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0129_auto_20241229_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailykill',
            name='assigned_to',
        ),
    ]
