# Generated by Django 3.1.3 on 2024-12-29 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0130_remove_dailykill_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailykill',
            name='livestock_category',
        ),
    ]
