# Generated by Django 3.1.3 on 2024-12-29 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portals', '0132_dailykill_livestock_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseasereport',
            name='stamp',
        ),
        migrations.CreateModel(
            name='YearlyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_submission', models.DateField()),
                ('sub_county', models.CharField(max_length=100)),
                ('ward_level', models.CharField(max_length=100)),
                ('submitted_by', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('uploaded_report', models.FileField(upload_to='monthly_reports/')),
                ('assigned_to_official', models.ForeignKey(blank=True, default=1, limit_choices_to={'is_official': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yearly_reports_official', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuarterlyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_submission', models.DateField()),
                ('sub_county', models.CharField(max_length=100)),
                ('ward_level', models.CharField(max_length=100)),
                ('submitted_by', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('uploaded_report', models.FileField(upload_to='monthly_reports/')),
                ('assigned_to_official', models.ForeignKey(blank=True, default=1, limit_choices_to={'is_official': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quartely_reports_official', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
