# Generated by Django 3.1.3 on 2024-12-30 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0134_auto_20241230_0638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practitioner',
            old_name='epmloyment_status',
            new_name='employment_status',
        ),
    ]
