# Generated by Django 3.1.3 on 2024-12-30 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0136_noobjection_county'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noobjection',
            name='county',
        ),
    ]
