# Generated by Django 3.1.3 on 2024-12-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0137_remove_noobjection_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slaughterhouse',
            name='livestock_slaughtered',
            field=models.CharField(max_length=255),
        ),
    ]
