# Generated by Django 3.1.3 on 2024-12-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0138_auto_20241230_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='slaughterhouse',
            name='slaughterhouse_status',
            field=models.CharField(default='municipal', max_length=50),
            preserve_default=False,
        ),
    ]
