# Generated by Django 3.1.3 on 2024-12-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0139_slaughterhouse_slaughterhouse_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='medical_license_status',
            field=models.CharField(choices=[('updated', 'Updated'), ('not_updated', 'Not Updated')], max_length=50),
        ),
        migrations.AlterField(
            model_name='slaughterhouse',
            name='slaughterhouse_status',
            field=models.CharField(choices=[('private', 'Private'), ('municipal', 'Municipal')], max_length=50),
        ),
    ]
