# Generated by Django 3.1.3 on 2024-12-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0141_auto_20241230_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='butcher',
            name='livestock_slaughtered',
            field=models.CharField(max_length=50),
        ),
    ]
