# Generated by Django 3.1.3 on 2024-02-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_vet_officer_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='vet_officer',
            name='county',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='vet_officer',
            name='inst_of_grad',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='vet_officer',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='vet_officer',
            name='registration_number',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='vet_officer',
            name='vet_category',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
