# Generated by Django 3.1.3 on 2024-03-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20240228_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vet_officer',
            name='country',
        ),
        migrations.RemoveField(
            model_name='vet_officer',
            name='inst_of_grad',
        ),
        migrations.RemoveField(
            model_name='vet_officer',
            name='kvb_number',
        ),
        migrations.RemoveField(
            model_name='vet_officer',
            name='location',
        ),
        migrations.RemoveField(
            model_name='vet_officer',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='vet_officer',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='vet_officer',
            name='vet_category',
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='inst_of_grad',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vet_category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
