# Generated by Django 4.2.11 on 2024-11-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_official_rename_is_student_user_is_official_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='official',
            old_name='department',
            new_name='employment_number',
        ),
        migrations.RenameField(
            model_name='official',
            old_name='location',
            new_name='sub_county',
        ),
        migrations.AddField(
            model_name='official',
            name='designation',
            field=models.CharField(default='ssss', max_length=50),
            preserve_default=False,
        ),
    ]
