# Generated by Django 3.1.3 on 2024-02-07 10:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_supplierproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='vet_officer',
            name='specialization',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
