# Generated by Django 4.2.14 on 2026-01-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_dairycooperative_user_is_cooperative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dairycooperative',
            name='cooperative_name',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='farm_name',
        ),
        migrations.AddField(
            model_name='user',
            name='cooperative_name',
            field=models.CharField(default='DAIRY COOPERATIVE SERVICES', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='farm_name',
            field=models.CharField(default='SOINFARM', max_length=100),
        ),
    ]
