# Generated by Django 3.1.3 on 2024-11-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20241119_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official',
            name='county',
            field=models.CharField(max_length=50),
        ),
    ]
