# Generated by Django 3.1.3 on 2024-02-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20240227_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='county',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
