# Generated by Django 3.1.3 on 2024-02-28 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_farmer_county'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer',
            old_name='county',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='vet_officer',
            old_name='county',
            new_name='country',
        ),
    ]
