# Generated by Django 6.0.5 on 2026-05-20 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_farm_id_alter_productitem_id_alter_profile_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agrovet',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('agrovet_name', models.CharField(max_length=100, null=True)),
                ('vmd_number', models.CharField(max_length=100, null=True)),
                ('qualification', models.CharField(max_length=100, null=True)),
                ('county', models.CharField(max_length=100, null=True)),
                ('subcounty', models.CharField(max_length=100, null=True)),
                ('town', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
