# Generated by Django 6.0.5 on 2026-05-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_agrovet'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_agrovet',
            field=models.BooleanField(default=False),
        ),
    ]
