# Generated by Django 6.0.5 on 2026-07-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_is_agrovet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agrovet',
            name='vmd_number',
        ),
        migrations.AddField(
            model_name='user',
            name='vmd_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
