# Generated by Django 6.0.5 on 2026-07-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_agrovet_vmd_number_user_vmd_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agrovet',
            name='agrovet_name',
        ),
        migrations.AddField(
            model_name='user',
            name='agrovet_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
