---
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 
      
deployment:
  tasks:
    - export DEPLOYPATH=/home/soinvetc/farmvet/vetWeb/soin
    - /bin/cp soin $DEPLOYPATH
    