name: Deploy to cPanel FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up FTP deployment
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.soinvet.com
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /soinvetc   # Change this to your server directory
        local-dir: .  # Change this to the directory containing your code
        exclude: .gitignore, .git/

    - name: Notify deployment status
      run: echo "Deployment to cPanel FTP completed successfully"
